name: Deploy to stage branch

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    name: Deploy stage to EC2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST}}
            USER_NAME: ${{secrets.USER_NAME}}

        run: |
          echo "HOSTNAME length: ${#HOSTNAME}"
          echo "USER_NAME length: ${#USER_NAME}"
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

              # Now we have got the access of EC2 and we will start the deploy .
              cd next-app-cicd-2
              git checkout main &&
              git fetch --all &&
              git reset --hard origin/main &&
              git pull origin main &&
              pnpm install &&
              pnpm  build &&
              pm2 restart http&&
              pm2 restart ws
              '


