---
name: Deploy to staging
on:
  push:
    branches:
      - main
jobs:
  redeploy_everything:
    name: Deploying everything to the staging cluster
    runs-on: ubuntu-latest

    steps:
      - name: SSH into server
        run: |

          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/ssh.key
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.STAGE_SERVER_IP }} >> ~/.ssh/known_hosts
          ssh -i ~/ssh.key  ${{secrets.STAGE_SERVER_IP}} << 'EOF'
          cd next-app-cicd-2
          git pull origin main
          pnpm install
          pnpm build 
          pm2 restart http 
          pm2 restart ws
          EOF
